fix patch display chinese
twmr/gerrit.el pull request #54
Opened 2024-10-05 06:43 UTC by shuxiao9058

fix issue #53

2024-10-12 04:40 UTC, shuxiao9058 commented
Do you have any idea about this PR?

2024-10-13 18:28 UTC, twmr requested changes
Hi @shuxiao9058! Your patch contains a lot of unnecessary white-space changes, because the actual code change is quite small. Can you please undo the white-space changes?
Thx

2024-10-13 18:28 UTC, twmr commented on gerrit-rest.el
> +		    'utf-8))
Have you tried using decode-buffer-region instead of decode-coding-string? The latter should supports an in-place replacement of the text.

2024-10-14 01:47 UTC, shuxiao9058 commented on gerrit-rest.el
> +		    'utf-8))
I have tried `decode-coding-region` before, but not worked. But now it works.

2024-10-14 19:40 UTC, merged

2024-10-14 19:40 UTC, twmr commented
Thx!